# Generated by Django 6.1 on 2026-09-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('especialidade', models.TextField(blank=True, null=True, verbose_name='Especialidade')),
                ('crm', models.CharField(max_length=20, verbose_name='CRM')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('localização', models.TextField(blank=True, null=True, verbose_name='Localização')),
                ('preco_consulta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da consulta')),
                ('classificacao_pacientes', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Classificação pelos pacientes')),
                ('genero', models.CharField(max_length=10, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Médico',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('genero', models.CharField(max_length=10, verbose_name='Gênero')),
                ('convenio_medico', models.CharField(max_length=100, verbose_name='Convênio médico')),
            ],
            options={
                'verbose_name': 'Paciente',
                'ordering': ['nome'],
            },
        ),
    ]
