# Generated by Django 6.1 on 2026-09-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas_cadastradas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora da consulta')),
                ('especialidade', models.TextField(blank=True, null=True, verbose_name='Especialidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas_cadastradas.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas_cadastradas.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'ordering': ['data_hora'],
            },
        ),
    ]
